name: imagepy
channels:
  - conda-forge
  - nsls2forge
dependencies:
  # 核心依赖
  - python=3.10.13
  - numpy=1.26.3
  - numba=0.60.0
  - numpy-stl=3.1.1
  - scipy=1.15.2
  # 图像处理
  - scikit-image=0.25.2
  - scikit-learn=1.6.1
  - pillow=11.1.0
  - imageio=2.37.0
  - tifffile=2025.3.30
  - pystackreg=0.2.8
  - pydicom=2.4.4
  # 数据处理
  - pandas=2.2.2
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - xlwt=1.3.0
  - shapely=2.1.0
  # UI 和可视化
  - wxpython=4.2.2
  - pypubsub=4.0.3
  - matplotlib=3.10.1
  - vispy=0.14.3
  - moderngl=5.9.1
  - freetype-py=2.5.1
  # 文档和格式支持
  - markdown=3.6
  - python-markdown-math=0.8
  - read-roi=1.6.0
  # 工具和实用程序
  - dulwich=0.22.8
  - tqdm=4.67.1
  - joblib=1.4.2
  - pywavelets=1.8.0
  - networkx=3.4.2
  - six=1.17.0
